"""Chagne : Enum to int

Revision ID: 2d86ad033837
Revises: 96a61332fafb
Create Date: 2026-01-26 11:30:42.016198

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2d86ad033837"
down_revision = "96a61332fafb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=mysql.ENUM("ADMIN", "USER"),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "lock_flg",
            existing_type=mysql.ENUM("UNLOCKED", "LOCKED"),
            type_=sa.Integer(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "lock_flg",
            existing_type=sa.Integer(),
            type_=mysql.ENUM("UNLOCKED", "LOCKED"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.Integer(),
            type_=mysql.ENUM("ADMIN", "USER"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
