"""remove uniquer in password reset table

Revision ID: 81bc20294849
Revises: 2d86ad033837
Create Date: 2026-01-29 14:46:17.451744

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81bc20294849"
down_revision = "2d86ad033837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("email"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("email"), ["email"], unique=True)

    # ### end Alembic commands ###
