"""change dob to Date

Revision ID: 84254a5b7a28
Revises: 81bc20294849
Create Date: 2026-02-04 14:04:29.878071

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "84254a5b7a28"
down_revision = "81bc20294849"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "dob",
            existing_type=mysql.DATETIME(),
            type_=sa.Date(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "dob",
            existing_type=sa.Date(),
            type_=mysql.DATETIME(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
