"""Change : Boolean to Enum

Revision ID: 96a61332fafb
Revises: 6a5ce47826a1
Create Date: 2026-01-26 10:16:53.424974

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "96a61332fafb"
down_revision = "6a5ce47826a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=mysql.TINYINT(display_width=1),
            type_=sa.Enum("ADMIN", "USER", name="user_status_enum"),
            nullable=False,
        )
        batch_op.alter_column(
            "lock_flg",
            existing_type=mysql.TINYINT(display_width=1),
            type_=sa.Enum("UNLOCKED", "LOCKED", name="lock_status_enum"),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "lock_flg",
            existing_type=sa.Enum("UNLOCKED", "LOCKED", name="lock_status_enum"),
            type_=mysql.TINYINT(display_width=1),
            nullable=True,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum("ADMIN", "USER", name="user_status_enum"),
            type_=mysql.TINYINT(display_width=1),
            nullable=True,
        )

    # ### end Alembic commands ###
